//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubsystemKKEP.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineOfDepartment
    {
        public int IdDepartment { get; set; }
        public int IdDiscipline { get; set; }
        public string CourseOfStudy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Discipline Discipline { get; set; }
    }
}
